# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=30, null=True)),
                ('ReleaseVersion', models.IntegerField(blank=True, null=True)),
                ('CurrentStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('PlanStartDate', models.DateTimeField()),
                ('PlanEndDate', models.DateTimeField()),
                ('LogDate', models.DateTimeField(auto_now_add=True)),
                ('Remarks', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
