# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisStatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatus',
            name='LogDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='PlanEndDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailystatus',
            name='PlanStartDate',
            field=models.DateField(),
        ),
    ]
