# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisStatus', '0002_auto_20180503_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatus',
            name='ReleaseVersion',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=999, null=True),
        ),
    ]
