# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisStatus', '0004_auto_20180503_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatus',
            name='LogDate',
            field=models.DateField(),
        ),
    ]
