# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisStatus', '0005_auto_20180507_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatus',
            name='LogDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
