# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisStatus', '0007_auto_20180507_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatusAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=30, null=True)),
                ('ReleaseVersion', models.CharField(blank=True, max_length=30, null=True)),
                ('CurrentStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('PlanStartDate', models.DateField()),
                ('PlanEndDate', models.DateField()),
                ('ScenariosCovered', models.CharField(blank=True, max_length=30, null=True)),
                ('LogDate', models.DateField(auto_now_add=True)),
                ('Remarks', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailystatusqc',
            name='IssuesLogged',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
