# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisStatus', '0009_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=30, null=True)),
                ('ReleaseVersion', models.CharField(blank=True, max_length=30, null=True)),
                ('PlanStartDate', models.DateField()),
                ('PlanEndDate', models.DateField()),
                ('LogDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectAuto',
        ),
    ]
