# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisStatus', '0010_auto_20180509_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatusauto',
            name='ScenariosInprogress',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dailystatusauto',
            name='TotalScenarios',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
