# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisStatus', '0013_auto_20180509_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatusPQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=30, null=True)),
                ('ReleaseVersion', models.CharField(blank=True, max_length=30, null=True)),
                ('CurrentStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('PlanStartDate', models.DateField(blank=True, null=True)),
                ('PlanEndDate', models.DateField(blank=True, null=True)),
                ('IssuesLogged', models.CharField(blank=True, max_length=30, null=True)),
                ('LogDate', models.DateField(auto_now_add=True)),
                ('Remarks', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=30, null=True)),
                ('ReleaseVersion', models.CharField(blank=True, max_length=30, null=True)),
                ('PlanStartDate', models.DateField()),
                ('PlanEndDate', models.DateField()),
                ('LogDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
