# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisStatus', '0014_dailystatuspq_projectpq'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectauto',
            name='TempPlanEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectauto',
            name='TempPlanStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpq',
            name='TempPlanEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpq',
            name='TempPlanStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectqc',
            name='TempPlanEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectqc',
            name='TempPlanStartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
