# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisStatus', '0015_auto_20180511_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectauto',
            name='Remarks',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projectpq',
            name='Remarks',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projectqc',
            name='Remarks',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
