# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisStatus', '0026_auto_20180618_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectauto',
            name='ProductStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpq',
            name='ProductStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectqc',
            name='ProductStatus',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailystatusauto',
            name='CurrentStatus',
            field=models.CharField(blank=True, choices=[('Scripting', 'Scripting'), ('Stability Phase', 'Stability Phase'), ('Scripting Completed', 'Scripting Completed')], max_length=100, null=True),
        ),
    ]
